---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ferretdb-system
resources:
  - ./../../base
images:
  - name: ferretdb-controller
    newName: ftechmax/ferretdb-controller
    newTag: '{{IMAGE_TAG}}'
