apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ferretdbusers.ftechmax.net
spec:
  group: ftechmax.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                database:
                  type: string
                roles:
                  type: array
                  items:
                    type: string

      subresources:
        status: {}
  scope: Cluster
  names:
    plural: ferretdbusers
    singular: ferretdbuser
    kind: FerretDbUser
    shortNames:
      - fdbu
