apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ferretdbusers.k8s.ftechmax.net
spec:
  group: k8s.ftechmax.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                database:
                  type: string
                secret:
                  type: string
                usernameKey:
                  type: string
                  description: Key in the secret for the username
                  default: database_username
                passwordKey:
                  type: string
                  description: Key in the secret for the password
                  default: database_password
                roles:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                state:
                  type: string
                  description: State of the created user (Creating, Ready, Error)
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: ferretdbusers
    singular: ferretdbuser
    kind: FerretDbUser
    shortNames:
      - fdbu
