apiVersion: v1
kind: ServiceAccount
metadata:
  name: ferretdb-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ferretdb-controller
rules:
  - apiGroups: ['k8s.ftechmax.net']
    resources: ['ferretdbusers']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['k8s.ftechmax.net']
    resources: ['ferretdbusers/status']
    verbs: ['get', 'update']
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ferretdb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ferretdb-controller
subjects:
  - kind: ServiceAccount
    name: ferretdb-controller
